# Generated by Django 5.1.5 on 2025-02-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('language', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
